language: python
python:
  - "2.6"
virtualenv:
  system_site_packages: true
before_install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r dev_requirements.txt --use-mirrors"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse; fi
install: python scc.py -h
before_script: python scc.py travis-merge
script: PYTHONPATH=. python test/TestMerge.py UnitTestMerge; PYTHONPATH=. python test/TestConfig.py TestGithub; PYTHONPATH=. python test/TestDeploy.py; PYTHONPATH=. python test/TestToken.py
